// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type Relationship string

const (
	RelationshipPending Relationship = "pending"
	RelationshipFriends Relationship = "friends"
	RelationshipBlocked Relationship = "blocked"
)

func (e *Relationship) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Relationship(s)
	case string:
		*e = Relationship(s)
	default:
		return fmt.Errorf("unsupported scan type for Relationship: %T", src)
	}
	return nil
}

type NullRelationship struct {
	Relationship Relationship
	Valid        bool // Valid is true if Relationship is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRelationship) Scan(value interface{}) error {
	if value == nil {
		ns.Relationship, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Relationship.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRelationship) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Relationship), nil
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Relation struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	UserID       uuid.UUID
	ReceiverID   uuid.UUID
	Relationship Relationship
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Login     string
	Password  string
	Email     string
}
